# Generated by Django 5.1 on 2024-10-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_cliente', models.CharField(max_length=6)),
                ('fecha_pedido', models.CharField(max_length=50)),
                ('total_pedido', models.CharField(max_length=50)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_entrega', models.CharField(max_length=50)),
                ('metodo_entrega', models.CharField(max_length=50)),
            ],
        ),
    ]
